package com.microapp.productservice.model;

import jakarta.persistence.*;
import java.math.BigDecimal;

/**
 * JPA entity representing a product stored in the H2 database.
 * <p>
 * The {@code id} is a database-generated Long (auto-increment) for simplicity.
 * The REST API exposes it as a String to keep the API contract flexible.
 */
@Entity
@Table(name = "products")
public class Product {

    /**
     * Primary key – auto-generated by the database (H2 IDENTITY strategy).
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable name of the product.
     * Must not be null.
     */
    @Column(nullable = false)
    private String name;

    /**
     * Unit price of the product.
     * Stored with up to 10 digits total and 2 decimal places.
     */
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;

    /**
     * Current available stock quantity.
     * Reduced by the async {@code OrderCreatedEvent} consumer.
     */
    @Column(nullable = false)
    private int stock;

    // ------------------------------------------------------------------
    // JPA requires a no-arg constructor
    // ------------------------------------------------------------------

    protected Product() {
    }

    /**
     * Convenience constructor for creating a new product (id is assigned by DB).
     *
     * @param name  Product name.
     * @param price Unit price.
     * @param stock Initial stock quantity.
     */
    public Product(String name, BigDecimal price, int stock) {
        this.name = name;
        this.price = price;
        this.stock = stock;
    }

    // ------------------------------------------------------------------
    // Getters and setters
    // ------------------------------------------------------------------

    public Long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public int getStock() {
        return stock;
    }

    public void setStock(int stock) {
        this.stock = stock;
    }

    @Override
    public String toString() {
        return "Product{id=" + id + ", name='" + name + "', price=" + price + ", stock=" + stock + '}';
    }
}
